config/routes.rb
Tsushin::Application.routes.draw do
  root :to => 'root#index'

  match '/login',                   :to => 'users/sessions#new',    :as => 'new_user_session'
  match '/auth/:provider/callback', :to => 'users/sessions#create', :as => 'create_user_session'

  post 'send/:template_name' => 'send#post'

  resources :templates do
    member do
      get 'activate'
      get 'duplicate'
    end
    collection do
      post 'try'
    end
  end

  resources :sent_emails, :only => [:index, :show]
  resources :jobs, :only => [:index]


  class AuthConstraint
    def matches?(request)
      Rails.application.config.authorized_users.include? request.session[:user_id]
    end
  end
  constraints(AuthConstraint.new) do
    match     'delayed_job' => DelayedJobWeb, :anchor => false
  end
end

app/models/sent_email.rb
class SentEmail < ActiveRecord::Base
  belongs_to :template
  attr_accessible :data, :message, :to_address
end

app/controllers/sent_emails_controller.rb
class SentEmailsController < ApplicationController
  def index
    @sent_grid = initialize_grid(SentEmail, :include => :template, :per_page => 50)
  end

  def show
    @sent_email = SentEmail.find(params[:id])
  end
end

app/views/sent_emails/index.html.erb
<%= grid(@sent_grid) do |g|
  g.column :name => 'Date', :attribute => 'created_at' do |sent|
    sent.created_at
  end

  g.column :name => 'To', :attribute => 'to_address' do |sent|
    sent.to_address
  end

  g.column :name => 'Template', :attribute => 'code', :model => 'Template' do |sent|
    sent.template.code
  end

  g.column :name => 'Data', :attribute => 'data' do |sent|
    content_tag :pre, sent.data, :class => 'index-data'
  end

  g.column :name => 'Message', :attribute => 'message' do |sent|
    content_tag :pre, sent.message, :class => 'index-message'
  end

  g.column do |sent|
    link_to('Show', sent_email_path(sent))
  end
end -%>

app/views/sent_emails/show.html.erb
<dl>
  <dt>Date</dt>
  <dd><pre><%= @sent_email.created_at %></pre></dd>
  <dt>To</dt>
  <dd><pre><%= @sent_email.to_address %></pre></dd>
  <dt>Template</dt>
  <dd><pre><%= link_to @sent_email.template.code, @sent_email.template %> (active=<%=@sent_email.template.active %>, displayed=<%=@sent_email.template.displayed %>)</pre></dd>
  <dt>Data</dt>
  <dd><pre class="show-data"><%= @sent_email.data %> </pre></dd>
  <dt>Message</dt>
  <dd><pre class="show-message"><%= @sent_email.message %></pre></dd>
</dl>