config/routes.rb
Tsushin::Application.routes.draw do
  root :to => 'root#index'

  match '/login',                   :to => 'users/sessions#new',    :as => 'new_user_session'
  match '/auth/:provider/callback', :to => 'users/sessions#create', :as => 'create_user_session'

  post 'send/:template_name' => 'send#post'

  resources :templates do
    member do
      get 'activate'
      get 'duplicate'
    end
    collection do
      post 'try'
    end
  end

  resources :sent_emails, :only => [:index, :show]
  resources :jobs, :only => [:index]


  class AuthConstraint
    def matches?(request)
      Rails.application.config.authorized_users.include? request.session[:user_id]
    end
  end
  constraints(AuthConstraint.new) do
    match     'delayed_job' => DelayedJobWeb, :anchor => false
  end
end

app/views/templates/_form.html.erb
<%= form_for(@template, :html => { :class => 'form-horizontal' }) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <div class="control-group">
      <%= f.label :code, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :code, :size => 80 %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :from, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :from, :class => 'input-xxlarge' %><br/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :reply_to, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :reply_to, :class => 'input-xxlarge' %><br/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :cc, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :cc, :class => 'input-xxlarge' %><br/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :subject, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :subject, :class => 'input-xxlarge' %><br/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :html, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :html, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :plain, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :plain, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :example, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :example, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </fieldset>

<% end %>

app/views/templates/edit.html.erb
<div class="row">
  <div class="col-md-12">
  </div>
</div>
<%= form_for @template, :remote => true do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label 'Template name' %>
      <%= f.text_field :code,     :class => 'form-control', :placeholder => 'Template name' %>
      <%= f.label :from %>
      <%= f.text_field :from,     :class => 'form-control', :placeholder => 'From' %>
      <%= f.label :reply_to %>
      <%= f.text_field :reply_to, :class => 'form-control', :placeholder => 'Reply To' %>
      <%= f.label :cc, 'CC' %>
      <%= f.text_field :cc,       :class => 'form-control', :placeholder => 'CC' %>
      <%= f.label :subject %>
      <%= f.text_field :subject,  :class => 'form-control', :placeholder => 'Subject' %>
      <br />
      <div class="tabbable">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#tab-html" data-toggle="tab">HTML</a></li>
          <li><a href="#tab-plain" data-toggle="tab">Plain</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="tab-html">
            <%= f.text_area :html, :class => 'form-control' %>
          </div>
          <div class="tab-pane" id="tab-plain">
            <%= f.text_area :plain, :class => 'form-control' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <%= f.label :example  %>
      <p>Use the "Try It" button below to use these example/test variables. This is what would be posted from DocDel in a normal operation. </p>
      <%= f.text_area :example, :class => 'form-control' %>
      <%= f.label 'To: (Required when using "Send It" button, but not save-able)' %>
      <%= text_field_tag :to, '', :class => 'form-control' %>
      <br />


    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-4">
      <button id="try-it" class="btn-block btn btn-success">Try It!</button>
    </div>
    <div class="col-md-4">
        <button id="send-it" class="btn-block btn btn-warning">Send It!</button>
        <div id="sent-alert"></div>
    </div>
    <div class="col-md-4">
      <%= f.submit 'Save It!', :confirm => 'Are you sure?', :class => 'btn-block btn btn-danger' %>
      <div id="saved-alert"></div>
    </div>
  </div>
<% end %>
<br />
<div class="row">
  <div class="col-md-12">
    <div class="tabbable">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">HTML</a></li>
        <li><a href="#tab2" data-toggle="tab">Plain</a></li>
        <li><a href="#tab3" data-toggle="tab">Raw</a></li>
        <li><a href="#tab4" data-toggle="tab">Errors</a></li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <div id="html-from"></div>
          <div id="html-subject"></div>
          <iframe id="html-body" src="about:blank" style="border: 1px solid grey; width:99%"></iframe>
        </div>
        <div class="tab-pane" id="tab2">
          <div id="plain-from"></div>
          <div id="plain-subject"></div>
          <pre id="plain-body"></pre>
        </div>
        <div class="tab-pane" id="tab3">
          <pre id="raw"></pre>
        </div>
        <div class="tab-pane" id="tab4" style="border: 1px solid red;">
          <iframe id="errors" src="about:blank" style="border: none; width:99%"></iframe>
        </div>
      </div>
    </div>
    <%= link_to 'Go back', :templates, :class => 'btn btn-primary' %>
    <br />
    <br />
    <br />
    <br />
  </div>
</div>

app/views/templates/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Template</th>
      <th>Created</th>
      <th>Updated</th>
      <th>From</th>
      <th>Subject</th>
      <th>Actions</th>
    </tr>
  </thead>

  <%= link_to 'New template', new_template_path, :class => 'btn btn-primary' %>

  <% @templates.group_by(&:code).each do |group, templates| %>
  <tbody style="overflow: auto; border-top: 2px solid #333333;">
    <% templates.each_with_index do |template, i| %>
    <tr class="<%= 'success' if template.current? %>">
      <td><%= link_to template.code, template %></td>
      <td><%= time_ago_in_words(template.created_at) %> ago</td>
      <td><%= time_ago_in_words(template.updated_at) %> ago</td>
      <td><code><%= template.from %></code></td>
      <td><code><%= template.subject %></code></td>
      <td>
        <%= link_to 'Edit', [:edit, template], :class => 'btn btn-warning' %>
        <%= link_to 'Duplicate', [:duplicate, template], :class => 'btn btn-info' %>
        <%= link_to 'Destroy', template, :class => 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Activate', [:activate, template], :class => 'btn btn-success', data: { confirm: 'Are you sure?' } unless template.current? %>
      </td>
    </tr>
    <% end %>
  </tbody>
  <% end %>
</table>

<br />

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @template.code %></h1>

Active
<pre>
<%= @template.active %>
</pre>

Displayed
<pre>
<%= @template.displayed %>
</pre>

From
<pre>
<%= @template.from %>
</pre>

Reply-To
<pre>
<%= @template.reply_to %>
</pre>

Cc
<pre>
<%= @template.cc %>
</pre>

Subject
<pre>
<%= @template.subject %>
</pre>

Html
<pre>
<%= @template.html %>
</pre>

Plain
<pre>
<%= @template.plain %>
</pre>

Example
<pre>
<%= @template.example %>
</pre>

<%= link_to 'Edit', [:edit, @template], :class => 'btn btn-primary'  %>
<%= link_to 'Back', templates_path, :class => 'btn btn-primary'  %>